name: Release Upload

on:
  release:
    types: [published]

jobs:
  release:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: (cd web && npm install)
      - name: Build with Gradle
        run: ./gradlew build -x test
      - id: modified_tag
        run: |
          tag_name="${{ github.event.release.tag_name }}"
          version=$(echo "$tag_name" | sed "s/v//")
          echo "::set-output name=version::$version"
      - name: Upload SolarThing Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./client/build/libs/client-0.0.1-SNAPSHOT.jar
          asset_name: solarthing-${{ steps.modified_tag.outputs.version }}.jar
          asset_content_type: application/octet-stream
      - name: Upload SolarThing GraphQL Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./graphql/build/libs/graphql-0.0.1-SNAPSHOT.jar
          asset_name: solarthing-graphql-${{ steps.modified_tag.outputs.version }}.jar
          asset_content_type: application/octet-stream
